# Generated by Django 3.1.7 on 2022-02-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0003_auto_20220129_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
