# Generated by Django 3.1.7 on 2022-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0005_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_code',
            field=models.CharField(default=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.CharField(default='efFx7nAEggtEWltazp29SGOKRcKLM35QbkjVM4JC', max_length=40, unique=True),
        ),
    ]
