# Generated by Django 3.1.7 on 2022-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0007_auto_20220206_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teacher_code',
            field=models.CharField(default='tmpmZW7vab1fgzoE', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
