# Generated by Django 3.1.7 on 2022-02-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0009_auto_20220206_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='14Nd6u6fccbVHHdBTwnDo18iIZrxEoi4I3a8XbAf', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teacher_code',
            field=models.CharField(default='bokNr7fOToOTeZSv', max_length=16, unique=True, verbose_name='Код'),
        ),
        migrations.DeleteModel(
            name='Cookie',
        ),
    ]
