# Generated by Django 3.1.7 on 2022-02-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0015_auto_20220219_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dinner_days',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='student',
            name='lunch_days',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='gf9JBWwy7JIp2Oz1UH9b5FSINIKDFdE562s3BD7n', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='2uHtDYuzS9IxvXFM', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
