# Generated by Django 3.1.7 on 2022-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0016_auto_20220219_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='e9YjbH3P9Ld2r0vadtxJw3MSjgy3W0pR6gV82YQe', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dinner_days',
            field=models.JSONField(default={'Вторник': False, 'Понедельник': False, 'Пятница': False, 'Среда': False, 'Четверг': False}),
        ),
        migrations.AlterField(
            model_name='student',
            name='lunch_days',
            field=models.JSONField(default={'Вторник': False, 'Понедельник': False, 'Пятница': False, 'Среда': False, 'Четверг': False}),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='V8sXoVpHx7MeNdGo', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
