# Generated by Django 3.1.7 on 2022-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0017_auto_20220219_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='tx420xTMAfMmgBH2SF9FrI2L48dJgj2DOaAaWn5O', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='EcBHvGoqz53pj33t', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
