# Generated by Django 3.1.7 on 2022-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0019_auto_20220219_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='U3YxQFkbI7qoqR0cfCIRsRWBSm4rVNuIYQl6TlAT', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dinner_days',
            field=models.JSONField(default={'Вт': False, 'Пн': False, 'Пт': False, 'Ср': False, 'Чт': False}),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lunch_days',
            field=models.JSONField(default={'Вт': False, 'Пн': False, 'Пт': False, 'Ср': False, 'Чт': False}),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='sXWbH4H4zPhvZ6JX', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
