# Generated by Django 3.1.7 on 2022-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0020_auto_20220219_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='CEMRBIWc2r2T1IgQvoyks2b2hJgNyQQvRAMGGmft', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='H69RT299a9STNgM7', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
