# Generated by Django 3.1.7 on 2022-02-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0021_auto_20220219_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='CppBzZ72pPiGAOCqOblw56fIQ8mvjGhwzE0iDl74', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_class',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='digitalDR.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='pzffyCk1ztWKfznS', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
