# Generated by Django 3.1.7 on 2022-02-27 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalDR', '0023_auto_20220220_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='54FPeFhJcmZbhoxPfUx7HPnddbv1chp09Z5u81eJ', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='OHSK1mENVACj2Pax', max_length=16, unique=True, verbose_name='Код'),
        ),
    ]
