# Generated by Django 3.1.7 on 2022-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0025_auto_20220227_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='customuser_ptr',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cookie',
            field=models.CharField(default='h0ojRwTiiHkDCveMDNvSOtDyH7UQn1cqdavmOFgV', max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
