# Generated by Django 3.1.7 on 2022-02-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0026_auto_20220228_0807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
