# Generated by Django 3.1.7 on 2022-03-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalDR', '0030_auto_20220228_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_days', models.JSONField(default={'Вт': False, 'Пн': False, 'Пт': False, 'Ср': False, 'Чт': False})),
                ('lunch_days', models.JSONField(default={'Вт': False, 'Пн': False, 'Пт': False, 'Ср': False, 'Чт': False})),
                ('is_accept', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='user',
        ),
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestUser',
        ),
        migrations.DeleteModel(
            name='UserMenu',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalDR.class'),
        ),
    ]
