# Generated by Django 3.1.7 on 2022-03-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0031_auto_20220310_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalDR.class'),
        ),
    ]
