# Generated by Django 3.1.7 on 2022-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0033_userinformation_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=20)),
                ('last_info', models.TextField(blank=True)),
                ('last_get_info', models.FloatField(blank=True)),
            ],
        ),
    ]
