# Generated by Django 3.1.7 on 2022-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0035_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='balance_last_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='balance_last_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='card_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
