# Generated by Django 3.1.7 on 2022-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0036_auto_20220410_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='balance_last_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
