# Generated by Django 3.1.7 on 2022-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0038_remove_userinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='balance_last_info',
            field=models.JSONField(blank=True),
        ),
    ]
