# Generated by Django 3.1.7 on 2022-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalDR', '0039_auto_20220417_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='balance_last_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
